apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  JWT_SECRET: mysecret
  AUTH_MONGO_URL: mongodb+srv://sooryanarayanantr_db_user:Eq9rCOopjJu8gOuo@cluster0.ksovhvv.mongodb.net/auth-db?appName=Cluster0
  USER_MONGO_URL: mongodb+srv://sooryanarayanantr_db_user:Eq9rCOopjJu8gOuo@cluster0.ksovhvv.mongodb.net/user-db?appName=Cluster0
  POSTGRES_URL: postgres://07b63c98aec53a2dcccd8f16f84196dc903fc960086443b0184b1190c043acc5:sk_U3V01tiPWIBLuUzSqIyfe@db.prisma.io:5432/postgres?sslmode=require