apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  GATEWAY_PORT: "3000"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  PROFILE_SERVICE_URL: "http://profile-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"